server:
  port: ${PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: flexswu

  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
        hbm2ddl:
          auto: update
    database: mysql
  profiles:
    include:
      - database
      - local


#frontend:
#  domain: ${FRONT_DOMAIN}
#


jwt:
  secret: ${JWT_SECRET}
